version: '3.6'

volumes:
  ghost-db:
  ghost-content:
    # driver: local-persist
    # driver_opts:
    #   mountpoint: ${PWD}/ghost

services:
  db:
    container_name: ghost-db
    image: mysql:5.7
    restart: always
    volumes:
      - ghost-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ghost
      MYSQL_ROOT_PASSWORD: password

  ghost:
    build: .
    container_name: ghost
    image: ghost-custom
    restart: always
    ports:
      - "2368:2368"
    volumes:
      - ghost-content:/var/lib/ghost/content
    environment:
      ENV: development
      NODE_ENV: development
      database__client: mysql
      database__connection__host: db
      database__connection__user: username
      database__connection__password: root
      database__connection__database: ghost
      storage__active: digitalocean # or aws
      GHOST_DO_KEY: DO_KEY
      GHOST_DO_SECRET: DO_SECRET
      GHOST_DO_REGION: DO_REGION
      GHOST_DO_BUCKET: DO_BUCKET
      GHOST_DO_ENDPOINT: DO_ENDPOINT
      GHOST_DO_SUBFOLDER: DO_SUBFOLDER
      GHOST_DO_SPACE_URL: DO_SPACE_URL